
version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - FRONTEND_URL=https://fleet-flow-7189cccb.base44.app
    volumes:
      - ./backend:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

  frontend-proxy:
    build: ./frontend-proxy
    ports:
      - "8080:8080"
    environment:
      - BACKEND_URL=http://backend:8000
      - FRONTEND_URL=https://fleet-flow-7189cccb.base44.app
    depends_on:
      - backend
    command: npm start

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend-proxy
