services:
  backend:
    build:
      context: ../backend
    env_file:
      - ../.env.example
    depends_on: [redis]
    ports:
      - "8000:8000"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
